### ISSUE TITLE
up to date NVDA release support

### ISSUE THREAD

**Issue by JanuszChmiel** [mush42/sonata-nvda#49]
Dear elite Python developers,
I would like to express my deepest possible programmers appreciation to you. Your addon have opened door to The world of high quality and freely available voices based on artificial iontelligence on neural network. Thanks to C and thanks to The Rust languages, The responsiveness is very good and The reliability and The stability of The addon and its dependencies is outstanding.
Unfortunately, NVDA developers are using newer and newer versions of python and of its dependency for NVDA.
Please how complex is to recode The Python Addon source so it could support The newest stable version of NVDA?
Or it would require many many changes?
I only believe, that new version of Python do not break The good communication between Python source of The addon and Neural voice model written iN C and Rust.
Sure. It is no problem for Me to use latest supported NVDA version.
COuld you provide some Python source code examples which would demonstrate how complex changes somebody would had to apply to The source code of this ammazing addon?

Thank you very very very much for your time and for your very complex and long time programmers work which you had to invest to this addon development.

My last question is rather NVDA development based.
Is it really necessary to use always The newest stable Python version so often while developing NVDA screen reader?

**Comment by Qchristensen** [comment]
Hi @JanuszChmiel - it's generally best to keep issues to ideally one specific issue (and in this case, to do with the Sonata add-on).

But just to your NVDA development questions - NVDA is actually often NOT on the most recent Python release.  The current release of Python is 3.12.4.  NVDA 2024.x is built with Python 3.11., which came out in October 2022: https://www.python.org/downloads/

See the API changes in https://www.nvaccess.org/files/nvda/releases/2024.3beta2/documentation/changes.html - as with any dependency, it is a tightrope between incorporating the latest features and maintaining support for older environments (We held off updating because we had previously been using the last release of Python which was compatible with Windows 7.  Hence, NVDA 2024.1 dropped support for Windows 7).
